//generate or change salary password
export const GENERATE_CHANGE_SALARY_PASS_REQUEST =
  "GENERATE_CHANGE_SALARY_PASS_REQUEST";
export const GENERATE_CHANGE_SALARY_PASS_SUCCESS =
  "GENERATE_CHANGE_SALARY_PASS_SUCCESS";
export const GENERATE_CHANGE_SALARY_PASS_FAIL =
  "GENERATE_CHANGE_SALARY_PASS_FAIL";

//change password
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_REQUEST_SUCCESS =
  "CHANGE_PASSWORD_REQUEST_SUCCESS";
export const CHANGE_PASSWORD_REQUEST_FAIL = "CHANGE_PASSWORD_REQUEST_FAIL";
